### ISSUE TITLE
Missing default template

### ISSUE THREAD

**Issue by ricciocri** [manala/ansible-role-haproxy#1]
Hello, it seems that you have not published the default template for the haproxy configuration, can you please verify ?

**Comment by hyvs** [comment]
Hi. For now, this role didn't provide haproxy templates. You need to declare them in your playbook.

Basic example : 

> /example-playbook/playbook.yml
```yaml
- hosts: all
  vars:
    manala_haproxy_config_template: "{{ playbook_dir }}/templates/haproxy.j2"
  roles:
    - role: manala.haproxy
```

> /example-playbook/templates/haproxy.j2
```yaml
global
    log 127.0.0.1 local0 err
    log 127.0.0.1 local1 notice

    ulimit-n    65536
    maxconn     15000

    chroot      /var/lib/haproxy
    user        haproxy
    group       haproxy
    daemon

defaults
    log     global
    default-server inter 3s fall 2 rise 2 slowstart 60s
    retries    3
    maxconn    100

frontend frontend_http
    bind {{ ansible_eth0.ipv4.address }}:80

    mode    http
    option  httplog
    option  forwardfor

    default_backend app_backend

backend app_backend
    mode   http
    server web-1 192.168.0.2:80
```
